# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            aliqin
tagline:          'alibaba telecom'
description:      'alibaba telecom'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'aliqin'
  url:            https://github.com/aliqin

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/aliqin/aliqin.github.io
