# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            aliqin
tagline:          'f2e team of alibaba telecom'
description:      'f2e team of alibaba telecom'
url:              http://aliqin.github.io
baseurl:          /
logo:             '/public/images/logo.png'

author:
  name:           'aliqin'
  url:            https://github.com/aliqin

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/aliqin
