baseurl = "http://quanfeng.tech/aliqin.github.io/"
title = "阿里通信前端团队"
theme = "casper"
languagecode = "zh-CN"
copyright = "Copyright © 2017. All rights reserved."
disqusshortname = "aliqin"
paginate = 5
pluralizelisttitles = false

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/vjeantet"
weight = 100

[params]
author = "Valère JEANTET"
authorlocation = "Paris, France"
authorwebsite = "http://vjeantet.fr"
bio = "IT software and Security Engineer, Open source enthusiast."
cover = "images/screen.png"
description = "Whatever the mind of man can conceive and believe, it can achieve."
githubName = "vjeantet"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "vjeantet"

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"